require_relative 'config_command'

module WhirledPeas
  module Command
    class Frames < ConfigCommand
      def self.description
        'Print out list of frames generated by application'
      end

      def start
        super

        require 'whirled_peas/animator/debug_consumer'
        require 'whirled_peas/animator/producer'

        Animator::Producer.produce(
          Animator::DebugConsumer.new, WhirledPeas.config.refresh_rate
        ) do |producer|
          config.application.start(producer)
        end
      end
    end
  end
end
