require_relative 'config_command'

module WhirledPeas
  module Command
    class Frames < ConfigCommand
      def self.description
        'Print out list of frames generated by application'
      end

      def start
        require 'whirled_peas/frame/debug_consumer'
        require 'whirled_peas/frame/producer'

        super

        Frame::Producer.produce(Frame::DebugConsumer.new) do |producer|
          config.driver.start(producer)
        end
      end
    end
  end
end
